### ISSUE TITLE
Add a button to export results to txt and png.

### ISSUE THREAD

**Issue by ghost** [Zarkonnen/GenGen#1]
I like how this generator produces planets that are not too detailed yet not too low res. Just perfect for a big-picture overview that is useful in a game project.

I'd love there to be these 3 buttons:

1) Export description to a downloadable .txt file
2) Screenshot of the rendered sphere planet to a png file, as a 512x512px size image.
3) Export the rectangular surface world map as a png file, atleast 2048px wide image.

**Comment by rubo77** [comment]
THis is already included. please close this issue
